apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 5s

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      maxLines: 5000
      derivedFields:
        - datasourceUid: prometheus
          matcherRegex: '"traceId":"([^"]+)"'
          name: traceId
          url: '$${__value.raw}'
